language: node_js
node_js:
- lts/*
git:
  depth: 3
addons:
  apt:
    packages:
    - expect-dev
cache:
- pip
- npm
install:
- npm ci
before_install:
- openssl aes-256-cbc -K $encrypted_d4a09416a845_key -iv $encrypted_d4a09416a845_iv -in .staging.key.json.enc -out .staging.key.json -d
- gcloud auth activate-service-account --key-file=.staging.key.json
stages:
- preparation
- name: build
- name: deploy
jobs:
  include:
  - stage: preparation
    env: APP_ENV=staging
    name: Check code, import documents, build samples, playground & boilerplate
    before_script:
    - scripts/unbuffer.sh gulp buildSamples
    - scripts/unbuffer.sh npm test
    script:
    - scripts/unbuffer.sh gulp buildPrepare
  - stage: build
    env: APP_ENV=staging
    install: &1
    - npm ci
    - pip install grow==0.7.4 --user
    name: Build Pages (EN)
    script: scripts/unbuffer.sh gulp buildPages --locales en
  - stage: deploy
    env: APP_ENV=staging
    before_script:
    - scripts/unbuffer.sh gulp buildFinalize
    - scripts/unbuffer.sh npm run smoke-test
    script:
    - gcloud app deploy --project=amp-dev-staging --quiet --version=1
